name: n2o_drivers_sources
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.2.0=pyh9f0ad1d_0
  - ca-certificates=2024.2.2=h56e8100_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=1.1.1w=h2bbff1b_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py39haa95532_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - python=3.9.13=h6244533_2
  - python_abi=3.9=2_cp39
  - sqlite=3.45.3=h2bbff1b_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py39haa95532_0
  - zeromq=4.3.5=hd77b12b_0
  - pip:
    - anyio==4.8.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==3.0.0
    - async-lru==2.0.4
    - attrs==24.3.0
    - babel==2.16.0
    - beautifulsoup4==4.12.3
    - bleach==6.2.0
    - bokeh==3.4.3
    - build==1.2.1
    - cachecontrol==0.14.0
    - category-encoders==2.6.4
    - certifi==2024.12.14
    - cffi==1.17.1
    - charset-normalizer==3.4.1
    - cleo==2.1.0
    - cloudpickle==3.1.1
    - cmdstanpy==1.2.5
    - colour==0.1.5
    - contourpy==1.3.0
    - crashtest==0.4.1
    - cycler==0.12.1
    - dbc-influxdb==0.12.0
    - debugpy==1.8.12
    - defusedxml==0.7.1
    - distlib==0.3.8
    - dtreeviz==2.2.2
    - dulwich==0.21.7
    - eli5==0.13.0
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - fastjsonschema==2.21.1
    - filelock==3.14.0
    - fonttools==4.55.5
    - fqdn==1.5.1
    - h11==0.14.0
    - holidays==0.65
    - httpcore==1.0.7
    - httpx==0.28.1
    - idna==3.10
    - importlib-metadata==8.6.1
    - importlib-resources==6.5.2
    - iniconfig==2.0.0
    - installer==0.7.0
    - ipykernel==6.29.5
    - ipython==8.18.1
    - ipywidgets==8.1.5
    - isoduration==20.11.0
    - jaraco-classes==3.4.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - joblib==1.4.2
    - json5==0.10.0
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-bokeh==4.0.5
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.11.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.15.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.3.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.13
    - keyring==24.3.1
    - kiwisolver==1.4.7
    - llvmlite==0.43.0
    - markupsafe==3.0.2
    - matplotlib==3.9.4
    - mistune==3.1.0
    - more-itertools==10.2.0
    - msgpack==1.0.8
    - nbclient==0.10.2
    - nbconvert==7.16.5
    - nbformat==5.10.4
    - notebook-shim==0.2.4
    - numba==0.60.0
    - numpy==2.0.2
    - overrides==7.7.0
    - packaging==24.2
    - pandas==2.2.3
    - pandocfilters==1.5.1
    - patsy==1.0.1
    - pexpect==4.9.0
    - pillow==11.1.0
    - pkginfo==1.10.0
    - platformdirs==4.2.2
    - pluggy==1.5.0
    - poetry-core==1.9.0
    - poetry-plugin-export==1.8.0
    - polars==1.20.0
    - prometheus-client==0.21.1
    - prompt-toolkit==3.0.50
    - prophet==1.1.6
    - psutil==6.1.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyale==1.2.0
    - pyaml==25.1.0
    - pyarrow==19.0.0
    - pycparser==2.22
    - pygments==2.19.1
    - pymannkendall==1.4.3
    - pyparsing==3.2.1
    - pyproject-hooks==1.1.0
    - pytest==8.3.4
    - python-dateutil==2.9.0.post0
    - python-graphviz==0.20.3
    - python-json-logger==3.2.1
    - pytz==2024.2
    - pywin32==308
    - pywin32-ctypes==0.2.2
    - pywinpty==2.0.14
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - rapidfuzz==3.9.0
    - reactivex==4.0.4
    - referencing==0.36.1
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.22.3
    - scikit-base==0.12.0
    - scikit-learn==1.5.2
    - scikit-optimize==0.10.2
    - scipy==1.13.1
    - seaborn==0.13.2
    - send2trash==1.8.3
    - setuptools==75.8.0
    - shap==0.46.0
    - shellingham==1.5.4
    - six==1.17.0
    - sktime==0.35.0
    - slicer==0.0.8
    - sniffio==1.3.1
    - soupsieve==2.6
    - stack-data==0.6.3
    - stanio==0.5.1
    - statsmodels==0.14.4
    - tabulate==0.9.0
    - terminado==0.18.1
    - threadpoolctl==3.5.0
    - tinycss2==1.4.0
    - tomli==2.2.1
    - tomlkit==0.12.5
    - tornado==6.4.2
    - tqdm==4.67.1
    - trove-classifiers==2024.4.10
    - types-python-dateutil==2.9.0.20241206
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - uncertainties==3.2.2
    - uri-template==1.3.0
    - urllib3==2.3.0
    - virtualenv==20.26.2
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - widgetsnbextension==4.0.13
    - xgboost==2.1.3
    - xlrd==2.0.1
    - xyzservices==2025.1.0
    - yellowbrick==1.5
    - zipp==3.21.0
